### PR TITLE
fix cso compression, add default cso parameter

### PR DESCRIPTION
**Pull request by framki**

### CODE REVIEW

**Comment by evertonstz** [comment]
There's a problem with your implementation for the default value when the user doesn't provide a compression value but searches for something:
```
pyNPS ❯ python3.7 pynps.py -c psp -dg -r usa -cso sonic
usage: pynps.py [-h] -c {psv,psp,psx,psm,_all} [-r {usa,eur,jap,asia}] [-dg]
                [-dd] [-dt] [-du] [-dde] [-cso [{1,2,3,4,5,6,7,8,9}]] [-u]
                [search]
pynps.py: error: argument -cso/--compress_cso: invalid choice: 'sonic' (choose from '1', '2', '3', '4', '5', '6', '7', '8', '9')
```
If I'm not wrong the intention is to provide "9" as a default value, right? It'll work without a search query.

**Comment by evertonstz** [comment]
Also, I don't feel confident in providing a default value for cso compression, since users tend to think the default value is somewhat the "best" value to use. I think I'll merge your fixes and leave the default cso value behind for now.

**Comment by framki** [comment]
ah, my bad
yes, the intention was to provide the default value, I was using this call which worked obviously:
```sh
python pynps.py -c psp -cso -dg exit
```
I got `9(default)` value from `maxcso`

**Comment by evertonstz** [comment]
Yeah, that's argparser, problematic as hell. I'm gonna give some thought if it's possible to implement default values without cannibalizing the query command. For now I'm going to merge your pull request and remove this part.

**Pull request merged**
