### PR TITLE
Added avatar download support.

### PR DESCRIPTION
**Pull request by smvueno**
I'm just a beginner at this and never studied python, but.
This seems to work fine for me, I tested it on my Linux system and were able to download all Avatars.

Please double-check my code in case I made a mistake or missed anything. 😃

### CODE REVIEW

**Comment by evertonstz** [comment]
What happens if:

- I call -A with -c "psv" ?
- I call -A with -c "ps3" -c "psv" ?
- I call -A with -c "ps3" -c "psv" -c "psx" -c "psp"?
- I call -AG with -c "psv" ?
- I call -AG with -c "psv" -c "ps3" ?
- I call -AG with -c "ps3" -c "psv" -c "psx" -c "psp"?

**Comment by evertonstz** [comment]
So, I tested you code and it seems I did a good job at preventing breakage when I implemented PSP xD. Still, there's some checks you need to do if you want this to be merged:

- check if avatars is available for the called system, if it's not, warn the user why the software is exiting in case of a single system, or why it's not being shown in case of multi-system. I think this is done at the create_args(). Multisearch seem to be working fine, my countermeasures to prevent errors in this case proved to be working;
- check if migrating from master to your fork don't break the current database the user already have: i.e adding the avatars to an already existing database either by full update using -u or partial update using -Au won't break it. Multi-system update is fine, I've countermeasures for this too, but you should also test it just in case;
- check why some raps are returning blank, see if it's not a bug in my code instead of them not being available;
- check if avatars are also working with download resume(-R), I'm not sure if I have countermeasures for that;
- are these flags working with avatars? -r, -s, -G/D/T/U/E, -eb, -cso, -zip, -l and -p, I probably have countermeasures for that, but I'm also not sure, so they should be tested to prevent erratic behavior;
- clean your pull request, as I previously said, I can't merge your code because it have conflicts with mine.

I think a better way to go about this pull request is closing it and making a new one, or you could just sort this one out.

Ping me up once you have sorted these things and I'll review and merge it. Cheers!

**Comment by evertonstz** [comment]
OK, I did a dumb thing. I tested your master in my master instead of in another branch... so I accidentally merged your code. Good thing is that I reverted it, bad thing is that you'll need to make another pull request in case you want to keep working in this.
I apologize!

**Comment by smvueno** [comment]
> Your code is asking for trouble...
> What happens if:
> 
> I call -A with -c "psv" ?
> I call -A with -c "ps3" -c "psv" ?
> I call -A with -c "ps3" -c "psv" -c "psx" -c "psp"?
> I call -AG with -c "psv" ?
> I call -AG with -c "psv" -c "ps3" ?
> I call -AG with -c "ps3" -c "psv" -c "psx" -c "psp"?
> I call -Au with -c "ps3" -c "psv" -c "psx" -c "psp"?
> I call -Au with -c"psv"

I'm a trouble maker 😎 

> When doing a pull request, not only to this project but also to others, it's also a good practice to stay as much "on point" as possible. A good example on why this is good is exactly this, I've the help lines already fixed here on my end just didn't push them, so your new help lines would conflict with mine, so I probably would be needing to go and pick your changes by hand and leave the other behind. A good way to go about this would be make these proposed changes in a different commit (so it can cherrypicked) or just make a new pull request for them.

Oh, that's cool! 
It's the first time for me actually using Github and do a pull request!
Thanks for the info, will keep this in mind for my next time! 

> So, I tested you code and it seems I did a good job at preventing breakage when I implemented PSP xD. Still, there's some checks you need to do if you want this to be merged:

Yeah, your code is foolproof "aka smvueno proof", your code survived the greatest terror of them all!
After testing my dirty fork with quite a few combinations with other consoles too. 
It seemed to work fine, but yes since there are no checks we might have unexpected bugs... 
Not sure how to implement checks for it tho, not that skilled yet. 
(Will hopefully get there eventually! ) 😄 

> check if avatars is available for the called system, if it's not, warn the user why the software is exiting in case of a single system, or why it's not being shown in case of multi-system. I think this is done at the create_args(). Multisearch seem to be working fine, my countermeasures to prevent errors in this case proved to be working;

> check if migrating from master to your fork don't break the current database the user already have: i.e adding the avatars to an already existing database either by full update using -u or partial update using -Au won't break it. Multi-system update is fine, I've countermeasures for this too, but you should also test it just in case;

> check why some raps are returning blank, see if it's not a bug in my code instead of them not being available in nopaystation, a good of doing this is reviewing the tsv file and compare the content with what you have in the database.

Your code is working perfectly, but it was missing from the avatars tsv file.
Double checked with the tsv file and noticed that the error was an empty rap cell.

> check if avatars are also working with download resume(-R), I'm not sure if I have countermeasures for that;

> are these flags working with avatars? -r, -s, -G/D/T/U/E, -eb, -cso, -zip, -l and -p, I probably have countermeasures for that, but I'm also not sure, so they should be tested to prevent erratic behavior;
> clean your pull request, as I previously said, I can't merge your code because it have conflicts with mine.

Your code might be a little bit over my head I'll need to study up a bit more before I can add the necessary checks.
I have never actually studied programming or python, just learning from trial and error atm.
I'm learning quite a bit tho from looking at your code and seeing your implementations!!
Your commentary inputs are helping even more!
But need to read up a bit more on file checks and python safety for avoiding bugs.

> OK, I did a dumb thing. I tested your master in my master instead of in another branch... so I accidentally merged your code when trying to push some of my own changes. Good thing is that I reverted it, bad thing is that you'll need to make another pull request in case you want to keep working in this.
> I apologize!

Omg! No, I'm sorry for sending the pull request in the first place! 
Maybe it would be better if I send it as a new branch instead if I would make a change?

**Comment by evertonstz** [comment]
> Omg! No, I'm sorry for sending the pull request in the first place!

Hell no, mate, don't be. I encourage you to send more! You have been very helpful with this PS3 implementation and I really like how dedicated you are, it's exactly this kind of people we need in open source.

> Maybe it would be better if I send it as a new branch instead if I would make a change?

No, the way you did was perfectly fine, I was the one that did the dumb thing and that's what I get for coding while drinking beer, lol.

> Your code might be a little bit over my head I'll need to study up a bit more before I can add the necessary checks.
I have never actually studied programming or python, just learning from trial and error atm.
I'm learning quite a bit tho from looking at your code and seeing your implementations!!
Your commentary inputs are helping even more!
But need to read up a bit more on file checks and python safety for avoiding bugs.

Don't worry too much about it, tho. I'll eventually merge your changes. I just can't merge it right now because I have no time to actually fully test the implementation, so I'll probably make a release without avatars and work over your code and make a iterative release some days from now. I can't hold a release anymore because I actually have a quite big bug with PSP games that I have to release the fix as fast as possible.

I think the best solution for this is: If you're running git on your computer, I encourage you to make a new pull request but revert [this commit](https://github.com/evertonstz/pynps/pull/19/commits/1dc535cce9732a020275460065fb8d3d00f867df) and make a new commit to just add the line for "-A" first and then pull request it to me. If you're doing everything from the Github website, I don't you can actually do this, so you can just pull request like you did with this one and I'll fix the incompatibilities later, should not be too hard.
After you pull request to me I'll merge your changes into another branch and run my tests from there, the good thing is that you can watch things there and see how I do things, might be a good learning material.

**Comment by smvueno** [comment]
> Hell no, mate, don't be. I encourage you to send more! You have been very helpful with this PS3 implementation and I really like how dedicated you are, it's exactly this kind of people we need in open source.

Thank you for the encouragement! I'm glad I could be at service ;) 

> No, the way you did was perfectly fine, I was the one that did the dumb thing and that's what I get for coding while drinking beer, lol.

Ah that explains a lot 😂 I usually do the same when I work at home late.
This peogramming project I'm mostly doing during my early mornings here in Japan.
Got too much time on my hands now since I work with tourism and we got no tourists here in Japan now lol.

> Don't worry too much about it, tho. I'll eventually merge your changes. I just can't merge it right now because I have no time to actually fully test the implementation, so I'll probably make a release without avatars and work over your code and make a iterative release some days from now. I can't hold a release anymore because I actually have a quite big bug with PSP games that I have to release the fix as fast as possible.

Let me know if you need any help with testing stuff. I'm good at finding bugs and testing the limits.

> I think the best solution for this is: If you're running git on your computer, I encourage you to make a new pull request but revert this commit and make a new commit to just add the line for "-A" first and then pull request it to me. If you're doing everything from the Github website, I don't think you can actually do this, so you can just pull request like you did with this one and I'll fix the incompatibilities later, should not be too hard.
> After you pull request to me I'll merge your changes into another branch and run my tests from there, the good thing is that you can watch things there and see how I do things, might be a good learning material.

I'm currently using the Github homepage since I was just using and testing your code in my Google colabs data hoarder project.
Will look at my code again and try sending another pull when I'm at home tomorrow.
Btw I really recommend to try your code on google colabs, googles servers and download speed is blazing fast.
Makes it a breeze to debug code downloading of whole pkgs and lists.

**Comment by smvueno** [comment]
> I have some university work to do this week, but I'm sure I'll be able to test everything in a week max.
Take your time, work comes first, family life second and hobbies + beer last xD

**Comment by evertonstz** [comment]
Nice! I'll be waiting for your pull request. If I need any help with debugging, I'll be sure to ping you!
Cheers!

**Pull request merged**
